USE `netland`;

CREATE TABLE `movies` (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titel VARCHAR(100) NOT NULL,
    duur VARCHAR(100) NOT NULL,
    datum_uitkomst VARCHAR(100) NULL,
    land_uitkomst ENUM('NL', 'UK', 'US') NOT NULL,
    omschrijving TEXT NOT NULL,
    trailer VARCHAR(100) NOT NULL
);

INSERT INTO `movies` (`titel`, `duur`, `datum_uitkomst`, `land_uitkomst`, `omschrijving`, `trailer`) VALUES 
	('Shaun of the dead', '99 min', '29 Maart 2004', 'UK', 'Shaun heeft een saai, eentonig en lamlendig leven. Hij werkt in een elektronicazaak en spendeert het overgrote deel van zijn vrije tijd met zijn beste vriend en huisgenoot Ed, in hun stamkroeg "The Winchester", of achter de spelcomputer. Bij hem thuis is het een bende, Hier komt echter abrupt verandering in. Op de dag dat zijn stiefvader hem weer eens heeft opgezocht om hem te berispen, en zijn vriendin Liz het met hem uitmaakt omdat Shaun niet in hun relatie investeert, breekt er een epidemie uit in het hele land. Het virus, dat kan worden overgedragen door het bloed, verandert mensen in bloeddorstige zombies nadat ze zijn gestorven. Shaun en zijn vriend Ed bedenken een plan waarmee ze zichzelf, Liz en de moeder van Shaun kunnen redden. Zo kan Shaun zich meteen bewijzen, vooral tegenover zijn ex-vriendin.', 'LIfcaZ4pC-4'),
    ('Hot Fuzz', '155 min', '14 Februari 2007', 'UK', 'Nicholas Angel is een getalenteerde politieagent in Londen. Omdat hij zó goed is, lijkt het alsof de andere agenten slecht zijn. Zijn superieuren sturen hem daarom naar het slaperige en criminaliteitsloze dorpje Sandford, waar al in twintig jaar niemand is vermoord. Het blijkt echter dat Sandford niet helemaal het rustige dorpje is dat het lijkt. Er gebeuren een aantal heel erg vreemde ongelukken, waarvan Nicholas de enige is die inziet dat het eigenlijk om moorden gaat. Iedereen doet hem af als een gestreste stadsagent, in een dorp als Sandford worden immers geen moorden gepleegd.', 'ayTnvVpj9t4'),
    ('The Worlds End', '109 min', '10 Juli 2013', 'UK', 'Gary King, een alcoholist van middelbare leeftijd, spoort zijn van hem vervreemde schoolvrienden op en overtuigt hen om de "Golden Mile" te voltooien: een tocht langs twaalf kroegen in Newton Haven, de stad waarin ze zijn opgegroeid. Als tieners hadden ze de kroegentocht al eens gedaan, maar waren er toen niet in geslaagd om de laatste kroeg, The Worlds End, te bereiken. Gary arriveert in Newton Haven met zijn vrienden Andy, Oliver, Steven en Peter. De zus van Oliver, Sam, om wiens genegenheid Gary en Steven nog in hun tienerjaren hebben gevochten, voegt zich ook even bij hen voor een drankje. In de toiletruimte van de vierde kroeg raakt Gary in gevecht met een tiener. Gary slaat diens hoofd eraf en ontmaskert hem als androïde. Garys vrienden voegen zich bij hem en een gevecht met meerdere androïden ontstaat, die ze met enige moeite winnen.', 'hFo7eJR2cvc'),
    ('Die Hard', '131 min', '15 Juli 1988', 'US', 'De film begint in Los Angeles, waar politieagent John McClane aanwezig is bij een kerstfeest in een kantoorgebouw genaamd Nakatomi Plaza met zijn vrouw Holly. McClane wordt naar het gebouw gebracht door de praatgrage chauffeur Argyle in een limousine. Argyle wacht in de ondergrondse parkeergarage totdat John terug van het feest komt.Als hij bij het feest is, ontmoet McClane Takagi, de baas van zijn vrouw Holly. Hij kan echter Holly niet vinden. Wanneer hij haar vindt, ontstaat er meteen een ruzie tussen hen. John besluit de feestruimte daarom te verlaten en gaat naar een kleine kamer vlak bij het feest. Daar doet hij zijn schoenen uit en rust hij wat uit vanwege een jetlag. Ondertussen valt een groep Duitse terroristen onder leiding van Hans Gruber het gebouw binnen, waarna het gebouw hermetisch wordt afgesloten. ', 'jaJuwKCmJbY'),
    ('De Aanslag', '144 min', '6 Februari 1986', 'NL', 'Nederland begin 1945. De bezetting van Nederland door de Duitsers duurt al bijna vijf jaar. De winter is extreem hard en de bevolking lijdt honger en kou. In het huis van de familie Steenwijk in Haarlem wordt geprobeerd om de allesbrander aan te houden en het schaarse eten te verdelen. Dan klinken er schoten. Peter Steenwijk, de oudste zoon, ziet politie-inspecteur Fake (spreek uit: faakuh) Ploeg in de sneeuw liggen. Ploeg stond bekend als landverrader en is vermoedelijk geliquideerd door het verzet. Hij is doodgeschoten voor het huis van de buren. Maar dan komen de buren naar buiten en leggen het lijk voor het huis van de familie Steenwijk. Angstig kruipt de familie bij elkaar, ze weten dat de Duitsers represailles zullen uitvoeren als vergelding voor de aanslag', 'ah1gDclO14U')